### ISSUE TITLE
Improve & expand documentation

### ISSUE THREAD

**Issue by ix5** [posativ/isso#797]
Isso's docs have grown over time and some instructions have become outdated. Other parts lack needed info or are just not very inviting to newcomers.

### Main problems
- Information scattered over code comments, README, docs, (old) GitHub issues
- Contribution guidelines are unclear to some people. @Guts complained about this in IRC and there should be some guidance on what kind of changes are favored and which will be rejected
- Several configurations mentioned in `Deploying` probably haven't been tested in years

### TODOs

(Not every item in this list must/should be addressed, this is just an overview of _possible_ improvements)

- [ ] Expand README, which serves as first point of contact for many people new to Isso
- [ ] Expand FAQ
- [ ] Review (obsolete?) tech such as Vagrant, Ansible, uWSGI whose configs might no longer work and investigate removing them
- [ ] Expand Troubleshooting with more common errors (survey GH issues for common culprits)
- [ ] Overhaul contributing section
  - [ ] Point out more ways to contribute
  - [ ] Link to "contributor-needed" label
  - [ ] Write out a policy of what might be accepted/rejected
- [ ] Document Isso's internals
   - [ ] Python part:
     - [ ] DB structure
     - [ ] Markdown rendering
     - [ ] Overview of libraries used
     - [ ] Document preferred coding style
   - [ ] Javascript part:
     - [ ] Overview of libraries used
     - [ ] `RequireJS` vs `CommonJS` format, AMD
     - [ ] What bundling/minification is
   - [ ] Create an overview of all the tools/libraries/services associated with the project
 - [ ] Expand testing section to not only cover python part
   - [ ] Testing with docker
   - [ ] Pointing out easier ways to debug
   - [ ] Once migration to webpack/pug/... is complete:
     - [ ] Explain internal structure of JS part and how to debug inside the browser console
     - [ ] Document unit testing via `jest`
     - [ ] Document e2e integration testing via `puppeteer` (and common errors)
     - [ ] Document preferred code style
- [ ] More purpose-oriented tagline (as opposed to "a disqus alternative")

**Comment by ix5** [comment]
Here's my take on an updated preview image (with slight borders), which is more real-life-like than the current preview at http://posativ.org/~tmp/isso-sample.png

![example-slim-border](https://user-images.githubusercontent.com/10212877/167038602-ee6ece09-8267-46e6-9b8f-db81280efdab.png)
